import React from 'react';
import axios from 'axios';
import Head from 'next/head'
import Detail from '../../components/Detail';
import Layout from '../../components/Layout';

export default function DetailMovie(props) {
  const { movie } = props;
  return (
    <Layout>
      <Head>
        <title>Detail Movie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center flex-1 flex-shrink-0 justify-center space-y-4">
        <Detail
          movie={movie}
        />
      </div>
    </Layout>
  );
}

export async function getServerSideProps(context) {
  const { query } = context;
  const id = query?.slug;

  const movieResp = await axios.get(`https://www.omdbapi.com/?apikey=ce92ed13&i=${id}`)
    .catch(err => {
      if (process.env.NODE_ENV === 'development') {
        console.error(err);
      }

      return null;
    });

  const movie = movieResp?.data;

  return {
    props: {
      movie: movie
    }
  }
}
